-- MySQL Script generated by MySQL Workbench
-- Fri Aug 12 23:27:27 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DBAmo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DBAmo` ;

-- -----------------------------------------------------
-- Schema DBAmo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DBAmo` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `DBAmo` ;

-- -----------------------------------------------------
-- Table `education`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `education` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `education` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_educ` VARCHAR(50) NOT NULL,
  `fecha_inicio` VARCHAR(10) NOT NULL,
  `fecha_final` VARCHAR(10) NOT NULL,
  `desc_educ` VARCHAR(150) NOT NULL,
  `person_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `persona_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `experiences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `experiences` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `experiences` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_exp` VARCHAR(45) NOT NULL,
  `fecha_inicio` VARCHAR(10) NOT NULL,
  `fecha_final` VARCHAR(10) NOT NULL,
  `desc_exp` VARCHAR(150) NOT NULL,
  `person_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `persona_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `persona` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `person` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `descPers` VARCHAR(150) NOT NULL,
  `imagen` VARCHAR(150) NOT NULL,
  `telefono` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projects` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `projects` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_proj` VARCHAR(45) NOT NULL,
  `desc_proj` VARCHAR(150) NOT NULL,
  `imagen_proj` VARCHAR(150) NOT NULL,
  `persona_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `persona_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `skill` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `skill` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imgen` VARCHAR(150) NOT NULL,
  `porcentaje` INT(45) NOT NULL,
  `persona_id` INT(11) NOT NULL,
  `color` varchar (255),
  PRIMARY KEY (`id`, `persona_id`))
ENGINE = InnoDB;


SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
